import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Shield, ShieldAlert, Key, CheckCircle } from 'lucide-react';
import { toast } from 'sonner';
import api from '../api/axios';
import { useAuth } from '../context/AuthContext';

const SecuritySettings = () => {
  const { user, login } = useAuth(); // We might not need login from context, but we have user object
  const [setupData, setSetupData] = useState(null);
  const [otp, setOtp] = useState('');
  const [loading, setLoading] = useState(false);
  const [mfaEnabled, setMfaEnabled] = useState(false);
  
  // Set initial status based on user prop
  useEffect(() => {
    if (user && user.mfaEnabled !== undefined) {
      setMfaEnabled(user.mfaEnabled);
    }
  }, [user]);

  const handleSetup = async () => {
    setLoading(true);
    try {
      const res = await api.post('/mfa/setup');
      setSetupData(res.data);
    } catch (err) {
      toast.error('Failed to generate MFA token');
    } finally {
      setLoading(false);
    }
  };

  const handleEnable = async (e) => {
    e.preventDefault();
    if (!otp || otp.length < 6) return toast.error('Enter a valid 6-digit code');
    
    setLoading(true);
    try {
      await api.post('/mfa/enable', { token: otp });
      toast.success('Multi-Factor Authentication Enabled!');
      setMfaEnabled(true);
      setSetupData(null);
      setOtp('');
      
      // Update local profile optionally
      if (user) {
         user.mfaEnabled = true;
         sessionStorage.setItem('user', JSON.stringify(user));
      }
    } catch (err) {
      toast.error(err.response?.data?.error || 'Invalid Token');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="py-12 max-w-4xl mx-auto">
      <div className="mb-12">
        <h1 className="text-4xl font-bold text-slate-900 mb-2 flex items-center gap-3">
          <Shield className="w-10 h-10 text-primary-400" /> Security Settings
        </h1>
        <p className="text-slate-500">Manage your account security and authentication methods</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* MFA Status Card */}
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} className="glass-card p-8 relative overflow-hidden">
          <div className="absolute top-0 right-0 p-32 bg-primary-500/5 rounded-bl-full pointer-events-none"></div>
          <h2 className="text-2xl font-bold text-slate-900 mb-6">Multi-Factor Authentication</h2>
          
          <div className="flex items-center gap-4 mb-8">
            <div className={`w-16 h-16 rounded-full flex items-center justify-center ${mfaEnabled ? 'bg-green-100 text-green-700 border border-green-500/30 shadow-[0_0_20px_rgba(34,197,94,0.2)]' : 'bg-red-500/20 text-red-400 border border-red-500/30'}`}>
               {mfaEnabled ? <CheckCircle className="w-8 h-8" /> : <ShieldAlert className="w-8 h-8" />}
            </div>
            <div>
              <h3 className="text-xl font-bold text-slate-900">Status: {mfaEnabled ? 'Enabled' : 'Disabled'}</h3>
              <p className="text-sm text-slate-500">{mfaEnabled ? 'Your account is highly secure.' : 'Your account is vulnerable to unauthorized access.'}</p>
            </div>
          </div>

          {!mfaEnabled && !setupData && (
            <button 
              onClick={handleSetup} 
              disabled={loading}
              className="glass-button w-full flex justify-center items-center gap-2"
            >
              {loading ? <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div> : <><Key className="w-5 h-5"/> Setup Authenticator App</>}
            </button>
          )}

          {mfaEnabled && (
            <div className="bg-white border border-slate-200 rounded-xl p-4 text-center text-sm text-slate-600">
              MFA is currently active. To disable it, please contact an administrator.
            </div>
          )}
        </motion.div>

        {/* MFA Setup Form (Conditional) */}
        <AnimatePresence>
          {setupData && !mfaEnabled && (
            <motion.div 
              initial={{ opacity: 0, x: 20 }} 
              animate={{ opacity: 1, x: 0 }} 
              exit={{ opacity: 0, scale: 0.95 }}
              className="glass-card p-8 border-primary-500/30 shadow-[0_0_30px_rgba(170,59,255,0.1)]"
            >
              <h2 className="text-xl font-bold text-slate-900 mb-4">Configure App</h2>
              <ol className="list-decimal pl-5 text-sm text-slate-600 space-y-4 mb-6">
                <li>Download an authenticator app like Google Authenticator or Authy.</li>
                <li>Scan the QR code below or enter the manual key.</li>
                <li>Enter the 6-digit code generated by your app.</li>
              </ol>

              <div className="bg-white p-4 rounded-2xl w-fit mx-auto mb-6 shadow-xl">
                 <img src={setupData.qrCode} alt="MFA QR Code" className="w-48 h-48 object-contain" />
              </div>
              
              <div className="bg-white p-3 rounded-xl mb-6 text-center border border-slate-200">
                 <p className="text-xs text-slate-500 mb-1">Manual Setup Key</p>
                 <p className="font-mono text-primary-400 font-bold tracking-widest break-all">{setupData.secret}</p>
              </div>

              <form onSubmit={handleEnable}>
                <div className="mb-4">
                  <input 
                    type="text" 
                    placeholder="Enter 6-digit code" 
                    value={otp}
                    onChange={(e) => setOtp(e.target.value.replace(/\D/g, '').slice(0,6))}
                    className="glass-input w-full text-center text-2xl tracking-[0.5em] font-mono"
                    maxLength="6"
                    required
                  />
                </div>
                <button 
                  type="submit" 
                  disabled={loading || otp.length < 6}
                  className="glass-button w-full flex justify-center items-center"
                >
                  {loading ? <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div> : 'Verify & Enable'}
                </button>
              </form>
            </motion.div>
          )}
        </AnimatePresence>

      </div>
    </div>
  );
};

export default SecuritySettings;
